// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj-Xu-ph8i6VEacv4gd_SBavbHwT6xC5g',
    appId: '1:198112268127:web:3e6fadd1934da846a9b0ea',
    messagingSenderId: '198112268127',
    projectId: 'nova-shop-c6622',
    authDomain: 'nova-shop-c6622.firebaseapp.com',
    storageBucket: 'nova-shop-c6622.firebasestorage.app',
    measurementId: 'G-TG31C8QFZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa5Q9lH4jRGoqg1WdenEAkbnu8nkmpjLo',
    appId: '1:198112268127:android:0ff14c8d1fc9c4eca9b0ea',
    messagingSenderId: '198112268127',
    projectId: 'nova-shop-c6622',
    storageBucket: 'nova-shop-c6622.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtaaeplHf1KkkUsWHK9WRHDuAb0RZfhME',
    appId: '1:198112268127:ios:74c74e45062ad009a9b0ea',
    messagingSenderId: '198112268127',
    projectId: 'nova-shop-c6622',
    storageBucket: 'nova-shop-c6622.firebasestorage.app',
    iosBundleId: 'com.example.novaShop',
  );
}
